version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-server
    env_file:
      - .env
    ports:
      - "${SERVER_PORT:-8000}:8000"
    networks:
      - rag-network
    restart: unless-stopped

networks:
  rag-network:
    external: true